### PR TITLE
Add trends summaries section

### PR DESCRIPTION
**Pull request by aikho**
Add section with blog posts that summarize trends and new findings in NLP.

### CODE REVIEW

**Comment by NirantK** [comment]
Do you think this section is better titled **Research Summaries and Trends**? Give the strong research focus this has?

**Comment by keon** [comment]
Thanks! and I'd prefer *Research Summaries and Trends*

**Comment by NirantK** [comment]
@keon done in https://github.com/keon/awesome-nlp/commit/79fd3e121f92ba925a81cf7e94a9106c0859320f

**Comment by keon** [comment]
@NirantK awesome!

**Comment by aikho** [comment]
Thank you for the rapid response to my pull request and such awesome repository!

**Pull request merged**
