### PR TITLE
Added ALBERT Sanskrit model

### PR DESCRIPTION
**Pull request by parmarsuraj99**
Added a section of blogs and tutorials for indic Langugaes and added an ALBERT model trained on Sanskrit

### CODE REVIEW

**Comment by NirantK** [comment]
The blog seems unpolished right now. I'm happy to add the `huggingface` model link. 

Can you please edit your PR to have the just the model? 
(I'm assuming your completely trained model will be updated on the same link)

**Comment by parmarsuraj99** [comment]
Thanks. I have made the changes. 

Can we add that [HuggingFace model list](https://huggingface.co/models) as this contains a lot of models with so many possible applications?

Could you please suggest how can I improve that blog?

**Comment by NirantK** [comment]
Let's skip the model list for now? Or raise a separate PR and we'll discuss there. 

On the blog, I'd start by fixing all the grammar snafus, typos and spelling mistakes. Then, reducing the blog to it's essentials: 

> What did you do differently from the original tutorial notebook?

**Comment by parmarsuraj99** [comment]
Thanks. I will surely update that.

**Pull request merged**
