### PR TITLE
added NLP in Bengali

### PR DESCRIPTION
**Pull request by sagorbrur**
Hello,
thanks for this beautiful curated list. 
I added NLP in Bengali for Bengali Language. 
If you think it mergable please merge.
regards
Sagor

# Contribution Guidelines

Please ensure your pull request adheres to the following guidelines:

- Search previous suggestions before making a new one, as yours may be a duplicate.
- Make an individual pull request for each suggestion.
- Use the following format: [Bookmark Title](link): Description.
- The title usually consists of several words. For bookmarks of an article or tutorial, use the title of the article.
- The description consists of one-two sentences about the bookmark. It is required.
- If the resource has 2 or more links please provide the Github repo link.
- Additions should be added to the bottom of the relevant category.
- New categories or improvements to the existing categorization are welcome. 
- Check your spelling and grammar.
- Make sure your text editor is set to remove trailing whitespace.
- The pull request and commit should have a useful title.

Thank you for your suggestions!

### CODE REVIEW

**Comment by NirantK** [comment]
Thanks for the PR and amazing contribution to Bangla/Bengali. 

Few quick observations:

1. The NLTK tokenizer is plausibly _worse_ than anything like StanfordNLP because it's simply a wrapper over the English tokenizer. Do you intend to share benchmarks why your wrapper is better?

2. Can you please add the pre-trained model, and how it is pre-trained for the `SentencePiece` tokenizer?

3. Can you please add the Bengali Word2vec model?

4. Can you please benchmarks/metrics for Bengali Word2vec model? 

5. Excellent choice to build a Bengali lib by wrapping over popular tools like gensim, NLTK! Why is this specific to Bangla and a not a wider list of supported languages where the language can be an init param?

**Comment by sagorbrur** [comment]
Hi,
Thank you so much for quick reply. 
1. NLTK is a popular tool for English language. Francky, I didn't know it's worse. It's good to know now. Actually I wanted to give nltk a shape for bengali tokenization. Because English and Bengali is quite similar language. Only difference is punctuation "।" . 
2. I already shared bengali sentencepiece pretrained model inside model/sp_model.model. 
3. I already upload trained model of bengali word2vec at google drive. I will provide the link tonight.
4. It will take time to calculate or evaluate bengali word2vec model. 
5. beuatiful question! Other language has enough resource for nlp. But in contrary bengali language is far behind from this. So I only try to develop a library only for bengali so that future bengali NLP researcher or developer maynot suffer from this scarcity.
thanks again.
regards
Sagor Sarker

**Comment by NirantK** [comment]
Sounds good. 

Add the download links to word2vec and sentencepiece model to your README and let me know here.

We'll review and merge after that

**Comment by sagorbrur** [comment]
Hi,
thank you.
After updating , I will inform here. 
regards
Sagor

**Comment by sagorbrur** [comment]
Hi,
I have added link of word2vec and sentencepiece model to README.
Please check. 
regards
Sagor

**Comment by NirantK** [comment]
Please add the Bengali specific link for fasttext as well. 

It'd be good to explicit that you are using bin or txt format in your README as well

**Comment by sagorbrur** [comment]
Hi,
thanks. 
I will trained fasttext and provide model link.
Also let you know here. 
regards
Sagor

**Comment by sagorbrur** [comment]
Hi @NirantK,
You can check now and if possible please merge.
thanks and regards
Sagor

**Comment by NirantK** [comment]
From previous:

On what data is the pre-trained model for the SentencePiece tokenizer trained on? What is the vocabulary size?

Same info for Word2vec and fasttext please?

**Comment by sagorbrur** [comment]
Hi,
thanks. 
Okay, after making this repo more elegant I will send pull request again. 
Your modification suggestions really helped me to make this repo more resourceful. 
thanks and regards
sagor

**Comment by NirantK** [comment]
Hey @sagorbrur - I'm closing this pull request for now

I encourage you to raise a new PR when you're ready! 
That way we can have a fresh discussion about your best work

**Comment by sagorbrur** [comment]
Hi @NirantK 
thank you. 
I will raise a new PR after making it ready.
thanks again for all the great advices.
regards
Sagor

**Pull request closed without merging**
